In [1]:
from datasets import load_dataset
import pandas as pd
import os

/Users/krish/Downloads/MindScope/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset = load_dataset("ShenLab/MentalChat16K")
dataset

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating train split: 100%|██████████| 16084/16084 [00:00<00:00, 42184.04 examples/s]

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output'],
        num_rows: 16084
    })
})

In [3]:
df = pd.DataFrame(dataset["train"])

print(df.shape)
print(df.columns)
df.head()

(16084, 3)
Index(['instruction', 'input', 'output'], dtype='str')

,instruction,input,output
0,You are a helpful mental health counselling as...,I've been struggling with my mental health for...,I understand that you've been dealing with a s...
1,You are a helpful mental health counselling as...,I've been feeling overwhelmed with my caregivi...,"Your situation is complex, and it's important ..."
2,You are a helpful mental health counselling as...,I've been feeling constantly anxious and unabl...,I can see that you're dealing with a great dea...
3,You are a helpful mental health counselling as...,"My mom has Alzheimer's, and I've been her prim...",I'm sorry to hear that your siblings' demands ...
4,You are a helpful mental health counselling as...,"I've tried setting boundaries, but it feels li...","Your concerns are valid, and it's crucial to p..."

In [4]:
reddit_df = df[["input"]].copy()
reddit_df.columns = ["text"]

print(reddit_df.shape)
reddit_df.head()

(16084, 1)

                                                text
0  I've been struggling with my mental health for...
1  I've been feeling overwhelmed with my caregivi...
2  I've been feeling constantly anxious and unabl...
3  My mom has Alzheimer's, and I've been her prim...
4  I've tried setting boundaries, but it feels li...

In [5]:
reddit_df.to_csv("../data/raw/reddit_mental_health.csv", index=False)

print("saved")

saved